# docker build --pull --rm -f "DockerFile" -t mediasoupvidya:latest "."
# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' recursing_payne
FROM node:16 AS stage-one

WORKDIR /app
RUN \
    set -x \
    && apt-get update \
    && apt-get install -y net-tools build-essential python3 python3-pip valgrind


COPY package-lock.json .
COPY package.json .
RUN npm install

COPY functions functions
COPY ssl ssl
COPY public public

# EXPOSE 3016/tcp
# EXPOSE 3016/udp
# EXPOSE 10000-10100

RUN npm i -g nodemon

CMD npm start 